[[Lua]]
arch = "aarch64"
git-tree-sha1 = "14f1abc9fc60b2636a828df2a50e9cba7f38536b"
os = "macos"

    [[Lua.download]]
    sha256 = "a09b53396940be9ac4c2562cff91b4f8b7bfc32324d43de491a1aa1ec9a29b18"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.aarch64-apple-darwin.tar.gz"
[[Lua]]
arch = "aarch64"
git-tree-sha1 = "9118f636f54d8200dad3349d27f7c8d5b33111a6"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "5fdfd5361f32d07195d0511a611ee552179da68682d679252b7381141e20ac79"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.aarch64-linux-gnu.tar.gz"
[[Lua]]
arch = "aarch64"
git-tree-sha1 = "54afd3ee6976e59a7262dbb024614881d051a88a"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "a0ab4b289ea9bb3a5c7305e4829027f6da113e3377a1843719cbfdd9519fc2eb"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.aarch64-linux-musl.tar.gz"
[[Lua]]
arch = "aarch64"
git-tree-sha1 = "448a315eb106e208dbdeef6ad6d73e423dfefab6"
os = "freebsd"

    [[Lua.download]]
    sha256 = "2c35af4636347df9ebc4628ddcd60ae13418f0e96c96bec3471aa55ac93e5a20"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.aarch64-unknown-freebsd.tar.gz"
[[Lua]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9e181e366a84e1dd8b8abfddafa22903d6388678"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "f55416276856b96682158e057b4bebf609933caf836002d1ae0d01a7a253d10f"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.armv6l-linux-gnueabihf.tar.gz"
[[Lua]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ab77ff8768e5f6b50497868043c003f6bf35230"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "a470e797beb2d73b1396a847dd3213ca17c99968765724216e17d50713452437"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.armv6l-linux-musleabihf.tar.gz"
[[Lua]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "35ec60a873d3d2d11472afddf01080bb53f4d646"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "86029e6310a8c11eb14cd687187671c37583d38c9024b216a2edddbcfe866b21"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.armv7l-linux-gnueabihf.tar.gz"
[[Lua]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0012a61c21be5e43925519b506334ef121de5f7"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "62749be2d8629a8e0d2ba6c4b3da992ee36b37b52261924ffeb2560b774e56d7"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.armv7l-linux-musleabihf.tar.gz"
[[Lua]]
arch = "i686"
git-tree-sha1 = "bd5c78eec5d14f3f56d829fbebfbe8010005dfc9"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "0ce79c74958d190c3e07e0be3f4e8f0682e86dcbb1ef2262b0603861ec1f5963"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.i686-linux-gnu.tar.gz"
[[Lua]]
arch = "i686"
git-tree-sha1 = "ee14d38304b88d5b63cf5773a49cb1f87494dcaf"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "1b1857d59d8701ad18b6022c20dd5d25cb78382b318d1e8becb059ce9b7d6666"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.i686-linux-musl.tar.gz"
[[Lua]]
arch = "i686"
git-tree-sha1 = "ee7a4bacf4dc164836ab8b8647847869c9885d14"
os = "windows"

    [[Lua.download]]
    sha256 = "8f93d3c474369a259423769dd01e8c72b613cab705a6468cc0292c794b2f2a26"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.i686-w64-mingw32.tar.gz"
[[Lua]]
arch = "powerpc64le"
git-tree-sha1 = "1d13ac9c08c21a5c61f6d58cccfcff39057d4c4f"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "7dbe76d249dc79d83a7f80901304c568ca7ed49ca4576f88405ac242811d6f0a"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.powerpc64le-linux-gnu.tar.gz"
[[Lua]]
arch = "riscv64"
git-tree-sha1 = "fce253258c168e86e64ed29eb9e3723f0107cae5"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "2fa56b6bb8125fbb8c0f2ec66e2b477e97fa72e164659fa7d8bba1e3d14a1412"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.riscv64-linux-gnu.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "466ee68f0d3f3fa31aa9822043c4c799d865241a"
os = "macos"

    [[Lua.download]]
    sha256 = "6dc60416fae1889d24b16a1126ad69ccff2dd3007de99b90b1eb2cf9ba3d4b73"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.x86_64-apple-darwin.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "44b0363d8d35f07bfd0e17a88a46e10e149c1d96"
libc = "glibc"
os = "linux"

    [[Lua.download]]
    sha256 = "9506ce1e708a5de92b2f61d2f395a7d7cc16fc7a9ee878ec269fe7ef8e57bc1d"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.x86_64-linux-gnu.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "704563991467dbdad0359b016df41fb642a83bff"
libc = "musl"
os = "linux"

    [[Lua.download]]
    sha256 = "092db7c3f887712a5df8becb1e53e70cf97f68280f261643c54ae42acac543ed"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.x86_64-linux-musl.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "4730abbc805740ab413e76af1dc3d91eee319160"
os = "freebsd"

    [[Lua.download]]
    sha256 = "6f1a1f4baba9202539b7835c8f3b54bdb638bb3806d4fb608342ba45f6895f92"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.x86_64-unknown-freebsd.tar.gz"
[[Lua]]
arch = "x86_64"
git-tree-sha1 = "1eb3bf050cbdde748e0abb83666fab89916948e3"
os = "windows"

    [[Lua.download]]
    sha256 = "2e1363c3104cbb217d149160c7da5cad3aa07dfca5c0092e895ddf02ef4a6421"
    url = "https://github.com/JuliaBinaryWrappers/Lua_jll.jl/releases/download/Lua-v5.5.0+0/Lua.v5.5.0.x86_64-w64-mingw32.tar.gz"
